from prometheus_client import Counter, Gauge, Histogram, make_asgi_app

# RED metrics for API requests.
HTTP_REQUESTS_TOTAL = Counter(
    "gymops_http_requests_total",
    "Total HTTP requests handled by GymOps API.",
    labelnames=("method", "path", "status_code"),
)

HTTP_REQUEST_DURATION_SECONDS = Histogram(
    "gymops_http_request_duration_seconds",
    "HTTP request latency in seconds.",
    labelnames=("method", "path"),
    buckets=(0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
)

HTTP_IN_PROGRESS = Gauge(
    "gymops_http_requests_in_progress",
    "In-flight HTTP requests.",
    labelnames=("method",),
)

# Domain metrics for GymOps workouts.
WORKOUT_SESSIONS_TOTAL = Counter(
    "gymops_workout_sessions_total",
    "Workout session lifecycle events.",
    labelnames=("action",),
)

WORKOUT_SETS_TOTAL = Counter(
    "gymops_workout_sets_total",
    "Total workout sets recorded.",
    labelnames=("kind",),
)

WORKOUT_VOLUME_KG_TOTAL = Counter(
    "gymops_workout_volume_kg_total",
    "Accumulated workout volume in kg (weight * reps).",
)

WORKOUT_SUMMARIES_TOTAL = Counter(
    "gymops_workout_summaries_total",
    "Workout summaries generated by source.",
    labelnames=("analysis_source", "ai_enabled"),
)

# ASGI endpoint for /metrics.
metrics_asgi_app = make_asgi_app()


def record_session_started() -> None:
    WORKOUT_SESSIONS_TOTAL.labels(action="started").inc()


def record_session_completed() -> None:
    WORKOUT_SESSIONS_TOTAL.labels(action="completed").inc()


def record_session_cancelled() -> None:
    WORKOUT_SESSIONS_TOTAL.labels(action="cancelled").inc()


def record_set_added(*, is_warmup: bool, weight: float, reps: int) -> None:
    WORKOUT_SETS_TOTAL.labels(kind="warmup" if is_warmup else "effective").inc()
    WORKOUT_VOLUME_KG_TOTAL.inc(max(weight, 0.0) * max(reps, 0))


def record_summary_generated(*, analysis_source: str, ai_enabled: bool) -> None:
    WORKOUT_SUMMARIES_TOTAL.labels(
        analysis_source=analysis_source or "unknown",
        ai_enabled="true" if ai_enabled else "false",
    ).inc()

